spring:
  jpa:
    hibernate:
      ddl-auto: create   # o update/create-drop en dev
    defer-datasource-initialization: true  # <-- clave: data.sql corre DESPUÃ‰S del schema
  sql:
    init:
      mode: always       # asegura que data.sql se ejecute
      platform: h2
